---

- name: Install supervisor
  easy_install: name=supervisor
  sudo: true

- name: Create supervisor config directory
  file: path=/etc/supervisor/conf.d state=directory
  sudo: true

- name: Copy supervisor configuration
  copy: src=supervisord.conf dest=/etc/supervisord.conf
  sudo: true

- name: Copy supervisor local configuration
  template: src=local.supervisord.conf.j2 dest=/etc/supervisor/conf.d/{{ project_name }}.conf
  sudo: true
  notify: Reload supervisor config
  when: local

- name: Copy supervisor production configuration
  template: src=prod.supervisord.conf.j2 dest=/etc/supervisor/conf.d/{{ project_name }}.conf
  sudo: true
  notify: Reload supervisor config
  when: not local

- name: Copy supervisord systemd config
  copy: src=supervisor.service dest=/etc/systemd/system/supervisor.service owner=root group=root mode=0744
  sudo: true

- name: Create supervisor project log folder
  sudo: true
  file: path=/var/log/{{ project_name }}/ owner={{ project_user_username }} group={{ project_user_group }} state=directory recurse=yes

- name: Copy logrotate configuration
  template: src=project_logrotate.j2 dest=/etc/logrotate.d/{{ project_name }}_supervisord
  sudo: true
  when: not local

- name: Ensure supervisord is running
  service: name=supervisor state=started enabled=true
  sudo: true
