---
# Install Elasticsearch Plugins
# Adapted from https://github.com/Traackr/ansible-elasticsearch
#
# You will need to define an array called 'elasticsearch_plugins' in your playbook or inventory, such that:
#
# elasticsearch_plugins:
#  - { name: '<plugin name>', url: '<[optional] plugin url>' }
#  - ...
# where if you were to install the plugin via bin/plugin, you would type:
#
# bin/plugin -install <plugin name>
#
# or
#
# bin/plugin -install <plugin name> -url <plugin url>

# Example for https://github.com/elasticsearch/elasticsearch-mapper-attachments (bin/plugin -install elasticsearch/elasticsearch-mapper-attachments/1.9.0):
# elasticsearch_plugins:
#  - { name: 'elasticsearch/elasticsearch-mapper-attachments/1.9.0' }
#
# Example for https://github.com/richardwilly98/elasticsearch-river-mongodb (bin/plugin -i com.github.richardwilly98.elasticsearch/elasticsearch-river-mongodb/1.7.1):
# elasticsearch_plugins:
#  - { name: 'com.github.richardwilly98.elasticsearch/elasticsearch-river-mongodb/1.7.1' }
#
# Example for https://github.com/imotov/elasticsearch-facet-script (bin/plugin -install facet-script -url http://dl.bintray.com/content/imotov/elasticsearch-plugins/elasticsearch-facet-script-1.1.2.zip):
# elasticsearch_plugins:
#  - { name: 'facet-script', url: 'http://dl.bintray.com/content/imotov/elasticsearch-plugins/elasticsearch-facet-script-1.1.2.zip' }

# Loop though elasticsearch_plugins and install them
- name: Removing plugins if they exist
  action: >
    shell /usr/share/elasticsearch/bin/plugin --remove {{ item.name }}
  with_items: elasticsearch_plugins
  ignore_errors: yes
  sudo: true
- name: Installing plugins Elasticsearch by name
  action: >
    shell /usr/share/elasticsearch/bin/plugin -install {{ item.name }}
  when: item.url is not defined
  with_items: elasticsearch_plugins
  ignore_errors: yes
  sudo: true
- name: Installing plugins Elasticsearch by URL
  action: >
    shell /usr/share/elasticsearch/bin/plugin -install {{ item.name }} -url {{ item.url }}
  when: item.url is defined
  with_items: elasticsearch_plugins
  ignore_errors: yes
  sudo: true
# Fix permissions
- file: >
    path="/usr/share/elasticsearch/plugins" state=directory
    owner={{ elasticsearch_user }} group={{ elasticsearch_group }}
    recurse=yes
  sudo: true
