---

- name: Install gunicorn
  pip: name=gunicorn virtualenv=/data/env/{{ project_name }}
  sudo: true
  sudo_user: "{{ project_user_username }}"
  when: not local
  
- name: Copy gunicorn configuration
  template: src=gunicorn.conf.j2 dest=/etc/gunicorn.conf
  sudo: true
  when: not local
